apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        command:
          - "mongod"
          - "--bind_ip"
          - "0.0.0.0" 
        ports:
          - containerPort: 27017
            name: mongocontainer