apiVersion: v1
kind: ConfigMap
metadata:
  name: extended-oas
data:
  manualroutes.json: |
    {
      "paths": {
        "/store-info": {
          "get": {
            "x-permission": {
              "allow": "allow_all"
            }
          }
        },
        "/inventory": {
          "post": {
            "x-permission": {
              "allow": "allow_create_new_inventory_item"
            }
          },
          "get": {
            "x-rond": {
              "requestFlow": {
                "policyName": "filter_inventory",
                "generateQuery": true,
                "queryOptions": {
                  "headerName": "x-security-query"
                }
              },
              "responseFlow": {
                "policyName": "protect_inventory_info"
              }
            }
          }
        }
      }
    }
